import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Anek_Latin } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// new shit for ur Anek Latin default font
const anek = Anek_Latin({
  variable: "--font-anek",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anek.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
